#pragma once

template <class T>
class CProxy_ILisaCOMControllerEvents : public IConnectionPointImpl<T, &__uuidof( _ILisaCOMControllerEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
