#pragma once

template <class T>
class CProxy_ILisaCOMEvents : public IConnectionPointImpl<T, &__uuidof( _ILisaCOMEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
